RegisterNetEvent('esx:playerLoaded')
AddEventHandler('esx:playerLoaded',function(xPlayer, isNew, skin)
    StatSetInt('MP0_SHOOTING_ABILITY', 120, true)
    StatSetInt('MP0_STAMINA', 100, true)
    StatSetInt('MP0_LUNG_CAPACITY', 100, true)
    StatSetInt('MP0_STEALTH_ABILITY', 100, true)

    SetPedConfigFlag(cache.ped, 424, true)
    SetPedConfigFlag(cache.ped, 438, true)
    SetPedConfigFlag(cache.ped, 122, true)
    SetPlayerStamina(cache.playerId, 1.0)
    SetPlayerTargetingMode(2)
    SetBlipAlpha(GetNorthRadarBlip(), 0)

    SetAudioFlag("LoadMPData", true)
    SetAudioFlag("DisableFlightMusic", true)
    SetAudioFlag("WantedMusicDisabled", true)
    SetAudioFlag("PoliceScannerDisabled", true)
    SetAudioFlag("OnlyAllowScriptTriggerPoliceScanner", true)
    SetAudioFlag("AllowPoliceScannerWhenPlayerHasNoControl", false)
    StartAudioScene("CHARACTER_CHANGE_IN_SKY_SCENE")

    SetWind(0)
    SetRadarZoom(1100)
    SetFlashLightKeepOnWhileMoving(true)
    SetWeaponDamageModifier(`WEAPON_UNARMED`, 0.5)

    PauseClock(true)
    ClearAllBrokenGlass()
end)