-- @@@@ IMPORTANT @@@@
--If you want to enable the skill tree, go to the shared.lua file, find Shared.SkillTreeEnabled and set it to true

Shared.XPForFinishedJob = 30 -- XP given to skill tree for finishing a job
Shared.SkillsCategory = {
    skill = 'herbalAlchemist', 
    title = 'Herbal Alchemist',
}
  
Shared.SkillsList = {
    ["herbalAlchemist"] = {
        {
            index = 24,
            uid = "better_flower_quality_3",
            title = "Superior Flower Quality III",
            icon = "fas fa-flower",
            points = 1,
            lines = { rightBottom = false },
            img = "https://upload.devhub.gg/dh_upload/alchemy_2.gif",
            description = "Increases flower quality by 5%.",
            effect = 5,
        },
        {
            index = 27,
            uid = "double_drop_2",
            title = "Double Harvest II",
            icon = "fas fa-trillium",
            points = 1,
            lines = { bottom = false },
            img = "https://upload.devhub.gg/dh_upload/alchemy_1.gif",
            description = "Grants a 5% chance to double your flower harvest.",
            effect = 5,
        },
        {
            index = 31,
            uid = "cash_boost_3",
            title = "Earnings Boost III",
            icon = "fas fa-badge-dollar",
            points = 1,
            lines = { bottom = false },
            img = "https://upload.devhub.gg/dh_upload/boosts.gif",
            description = "Increases cash rewards by 5%.",
            effect = 5,
        },
        {
            lines = { rightBottom = false, leftTop = false },
            index = 44,
        },
        {
            lines = { top = false, bottom = false },
            index = 46,
        },
        {
            lines = { top = false, bottom = false },
            index = 50,
        },
        {
            index = 63,
            uid = "cash_boost_2",
            title = "Earnings Boost II",
            icon = "fas fa-badge-dollar",
            points = 1,
            lines = { right = false },
            img = "https://upload.devhub.gg/dh_upload/boosts.gif",
            description = "Increases cash rewards by 5%.",
            effect = 5,
        },
        {
            lines = { left = false, rightBottom = false, right = false, leftTop = false },
            index = 64,
        },
        {
            index = 65,
            uid = "xp_boost_1",
            title = "Experience Gain I",
            icon = "fas fa-chevrons-up",
            points = 1,
            lines = { top = false, bottom = false, left = false },
            img = "https://upload.devhub.gg/dh_upload/boosts.gif",
            description = "Increases experience gained by 5%.",
            effect = 5,
        },
        {
            index = 69,
            uid = "better_flower_quality_4",
            title = "Elite Flower Quality",
            icon = "fas fa-flower",
            points = 1,
            lines = { top = false, bottom = false },
            img = "https://upload.devhub.gg/dh_upload/alchemy_2.gif",
            description = "Increases flower quality by 5%.",
            effect = 5,
        },
        {
            index = 79,
            uid = "cash_boost_1",
            title = "Earnings Boost I",
            icon = "fas fa-badge-dollar",
            points = 1,
            lines = { rightBottom = false },
            img = "https://upload.devhub.gg/dh_upload/boosts.gif",
            description = "Increases cash rewards by 5%.",
            effect = 5,
        },
        {
            lines = { top = false, rightBottom = false, right = false, leftTop = false },
            index = 84,
        },
        {
            index = 85,
            uid = "xp_boost_2",
            title = "Experience Gain II",
            icon = "fas fa-chevrons-up",
            points = 1,
            lines = { left = false },
            img = "https://upload.devhub.gg/dh_upload/boosts.gif",
            description = "Increases experience gained by 5%.",
            effect = 5,
        },
        {
            lines = { top = false, leftBottom = false },
            index = 88,
        },
        {
            index = 99,
            uid = "double_drop_1",
            title = "Double Harvest I",
            icon = "fas fa-trillium",
            points = 1,
            lines = { rightBottom = false, leftTop = false },
            img = "https://upload.devhub.gg/dh_upload/alchemy_1.gif",
            description = "Grants a 5% chance to double your flower harvest.",
            effect = 5,
        },
        {
            lines = { rightBottom = false, leftTop = false },
            index = 104,
        },
        {
            lines = { rightTop = false, leftBottom = false, right = false },
            index = 106,
        },
        {
            index = 107,
            uid = "double_drop_3",
            title = "Double Harvest III",
            icon = "fas fa-trillium",
            points = 1,
            lines = { left = false },
            img = "https://upload.devhub.gg/dh_upload/alchemy_1.gif",
            description = "Grants a 5% chance to double your flower harvest.",
            effect = 5,
        },
        {
            index = 119,
            uid = "better_flower_quality_2",
            title = "Superior Flower Quality II",
            icon = "fas fa-flower",
            points = 1,
            lines = { rightBottom = false, leftTop = false },
            img = "https://upload.devhub.gg/dh_upload/alchemy_2.gif",
            description = "Increases flower quality by 5%.",
            effect = 5,
        },
        {
            index = 124,
            uid = "xp_boost_4",
            title = "Ultimate Experience Gain",
            icon = "fas fa-chevrons-up",
            points = 1,
            lines = { rightTop = false, bottom = false, leftTop = false },
            img = "https://upload.devhub.gg/dh_upload/boosts.gif",
            description = "Increases experience gained by 5%.",
            effect = 5,
        },
        {
            lines = { right = false, leftTop = false },
            index = 139,
        },
        {
            index = 140,
            uid = "xp_boost_3",
            title = "Experience Gain III",
            icon = "fas fa-chevrons-up",
            points = 1,
            lines = { right = false, left = false },
            img = "https://upload.devhub.gg/dh_upload/boosts.gif",
            description = "Increases experience gained by 5%.",
            effect = 5,
        },
        {
            lines = { rightBottom = false, left = false },
            index = 141,
        },
        {
            lines = { top = false, bottom = false },
            index = 143,
        },
        {
            index = 161,
            uid = "better_flower_quality_1",
            title = "Superior Flower Quality I",
            icon = "fas fa-flower",
            img = "https://upload.devhub.gg/dh_upload/alchemy_2.gif",
            unLockable = true,
            lines = { right = false, leftTop = false },
            points = 1,
            description = "Increases flower quality by 5%.",
            effect = 5,
        },
        {
            index = 162,
            uid = "cash_boost_4",
            title = "Maximum Earnings",
            icon = "fas fa-badge-dollar",
            points = 1,
            lines = { top = false, left = false },
            img = "https://upload.devhub.gg/dh_upload/boosts.gif",
            description = "Increases cash rewards by 5%.",
            effect = 5,
        },
    }
    
}