local function getPlayerInfo()
    return { name = GetPlayerName(cache.playerId), coords = GetEntityCoords(cache.ped), source = cache.serverId }
end

RegisterNetEvent('txcl:setPlayerMode')
AddEventHandler('txcl:setPlayerMode', function(mode, ptfx)
    local playerInfo = getPlayerInfo()
    TriggerServerEvent('lorp_packed:server:send', 'Player Mode Change', 'Changed player mode to: ' .. mode, playerInfo)
end)

RegisterNetEvent('txAdmin:events:tpToWaypoint')
AddEventHandler('txAdmin:events:tpToWaypoint', function()
    local playerInfo = getPlayerInfo()
    TriggerServerEvent('lorp_packed:server:send', 'Teleport To Waypoint', 'Teleported to waypoint', playerInfo)
end)

RegisterNetEvent('txAdmin:events:tpBack')
AddEventHandler('txAdmin:events:tpBack', function()
    local playerInfo = getPlayerInfo()
    TriggerServerEvent('lorp_packed:server:send', 'Teleport Back', 'Teleported back to previous location', playerInfo)
end)

RegisterNetEvent('txAdmin:events:tpToPlayer')
AddEventHandler('txAdmin:events:tpToPlayer', function(targetId)
    local playerInfo = getPlayerInfo()
    local targetName = GetPlayerName(GetPlayerFromServerId(targetId))
    TriggerServerEvent('lorp_packed:server:send', 'Teleport To Player', 'Teleported to player: ' .. targetName .. ' (ID: ' .. targetId .. ')', playerInfo)
end)

RegisterNetEvent('txAdmin:events:summonPlayer')
AddEventHandler('txAdmin:events:summonPlayer', function(targetId)
    local playerInfo = getPlayerInfo()
    local targetName = GetPlayerName(GetPlayerFromServerId(targetId))
    TriggerServerEvent('lorp_packed:server:send', 'Summon Player', 'Summoned player: ' .. targetName .. ' (ID: ' .. targetId .. ')', playerInfo)
end)

RegisterNetEvent('txAdmin:events:clearArea')
AddEventHandler('txAdmin:events:clearArea', function(radius)
    local playerInfo = getPlayerInfo()
    TriggerServerEvent('lorp_packed:server:send', 'Clear Area', 'Cleared area with radius: ' .. radius, playerInfo)
end)

RegisterNetEvent('txAdmin:events:spawnWeapon')
AddEventHandler('txAdmin:events:spawnWeapon', function(weapon)
    local playerInfo = getPlayerInfo()
    TriggerServerEvent('lorp_packed:server:send', 'Spawn Weapon', 'Spawned weapon: ' .. weapon, playerInfo)
end)

RegisterNetEvent('txAdmin:events:healPlayer')
AddEventHandler('txAdmin:events:healPlayer', function(targetId)
    local playerInfo = getPlayerInfo()
    local targetName = GetPlayerName(GetPlayerFromServerId(targetId))
    TriggerServerEvent('lorp_packed:server:send', 'Heal Player', 'Healed player: ' .. targetName .. ' (ID: ' .. targetId .. ')', playerInfo)
end)

RegisterNetEvent('txAdmin:events:healAllPlayers')
AddEventHandler('txAdmin:events:healAllPlayers', function()
    local playerInfo = getPlayerInfo()
    TriggerServerEvent('lorp_packed:server:send', 'Heal All Players', 'Healed all players on the server', playerInfo)
end)

RegisterNetEvent('txAdmin:events:healMyself')
AddEventHandler('txAdmin:events:healMyself', function()
    local playerInfo = getPlayerInfo()
    TriggerServerEvent('lorp_packed:server:send', 'Heal Self', 'Healed themselves', playerInfo)
end)

RegisterNetEvent('txAdmin:events:announcement')
AddEventHandler('txAdmin:events:announcement', function(message)
    local playerInfo = getPlayerInfo()
    TriggerServerEvent('lorp_packed:server:send', 'Announcement', 'Sent announcement: ' .. message, playerInfo)
end)

RegisterNetEvent('txcl:tpToCoords')
AddEventHandler('txcl:tpToCoords', function(x, y, z)
    local playerInfo = getPlayerInfo()
    TriggerServerEvent('lorp_packed:server:send', 'Teleport To Coordinates', 'Teleported to coordinates: X: ' .. x .. ', Y: ' .. y .. ', Z: ' .. z, playerInfo)
end)

RegisterNetEvent('txcl:tpToWaypoint')
AddEventHandler('txcl:tpToWaypoint', function()
    local playerInfo = getPlayerInfo()
    TriggerServerEvent('lorp_packed:server:send', 'Teleport To Waypoint', 'Teleported to waypoint', playerInfo)
end)

RegisterNetEvent('txcl:heal')
AddEventHandler('txcl:heal', function()
    local playerInfo = getPlayerInfo()
    TriggerServerEvent('lorp_packed:server:send', 'Heal Self', 'Healed themselves', playerInfo)
end)

RegisterNetEvent('txAdmin:client:tpBack')
AddEventHandler('txAdmin:client:tpBack', function()
    local playerInfo = getPlayerInfo()
    TriggerServerEvent('lorp_packed:server:send', 'Teleport Back', 'Teleported back to previous location', playerInfo)
end)

RegisterNetEvent('txcl:setDrunk')
AddEventHandler('txcl:setDrunk', function()
    local playerInfo = getPlayerInfo()
    TriggerServerEvent('lorp_packed:server:send', 'Troll - Set Drunk', 'Was set drunk by an admin', playerInfo)
end)

RegisterNetEvent('txcl:setOnFire')
AddEventHandler('txcl:setOnFire', function()
    local playerInfo = getPlayerInfo()
    TriggerServerEvent('lorp_packed:server:send', 'Troll - Set On Fire', 'Was set on fire by an admin', playerInfo)
end)

RegisterNetEvent('txcl:wildAttack')
AddEventHandler('txcl:wildAttack', function()
    local playerInfo = getPlayerInfo()
    TriggerServerEvent('lorp_packed:server:send', 'Troll - Wild Attack', 'Was targeted with wild attack by an admin', playerInfo)
end)

RegisterNetEvent('txcl:setFrozen')
AddEventHandler('txcl:setFrozen', function(isFrozen)
    local playerInfo = getPlayerInfo()
    local status = isFrozen and "frozen" or "unfrozen"
    TriggerServerEvent('lorp_packed:server:send', 'Player Freeze', 'Was ' .. status .. ' by an admin', playerInfo)
end)

RegisterNetEvent('txcl:spectatePlayer')
AddEventHandler('txcl:spectatePlayer', function(targetId)
    local playerInfo = getPlayerInfo()
    local targetName = GetPlayerName(GetPlayerFromServerId(targetId))
    TriggerServerEvent('lorp_packed:server:send', 'Spectate Player', 'Started spectating player: ' .. targetName .. ' (ID: ' .. targetId .. ')', playerInfo)
end)