Config = {}

Config.Language = 'en'

Config.Killfeed = {
    MaxEntries = 5,
    Duration = 5,
    DeathCooldown = 3000,
}

Config.KdHud = {
    Enabled = false,
}

Config.ClanTag = {
    MaxLength = 8,
}

Config.Streaks = {
    Enabled = true,
    Milestones = {
        { count = 3,  label = 'Double Down' },
        { count = 5,  label = 'Killing Spree' },
        { count = 7,  label = 'Rampage' },
        { count = 10, label = 'Unstoppable' },
        { count = 15, label = 'Godlike' },
        { count = 20, label = 'Legendary' },
    },
}

Config.WeaponLabels = {
    [GetHashKey('WEAPON_FALL')]                 = 'Fell to Death',
    [GetHashKey('WEAPON_DROWNING')]             = 'Drowned',
    [GetHashKey('WEAPON_DROWNING_IN_VEHICLE')]  = 'Drowned',
    [GetHashKey('WEAPON_FIRE')]                 = 'Burned',
    [GetHashKey('WEAPON_EXPLOSION')]            = 'Exploded',
    [GetHashKey('WEAPON_BLEEDING')]             = 'Bled Out',
    [GetHashKey('WEAPON_ELECTRIC_FENCE')]       = 'Electrocuted',
    [GetHashKey('WEAPON_BARBED_WIRE')]          = 'Barbed Wire',
    [GetHashKey('WEAPON_EXHAUSTION')]           = 'Exhaustion',
    [GetHashKey('WEAPON_HIT_BY_WATER_CANNON')]  = 'Water Cannon',
    [GetHashKey('WEAPON_RAMMED_BY_CAR')]        = 'Ran Over',
    [GetHashKey('WEAPON_RUN_OVER_BY_CAR')]      = 'Ran Over',
    [GetHashKey('WEAPON_VEHICLE')]              = 'Vehicle',
    [GetHashKey('WEAPON_UNARMED')]       = 'Fists',
    [GetHashKey('WEAPON_KNIFE')]         = 'Knife',
    [GetHashKey('WEAPON_NIGHTSTICK')]    = 'Nightstick',
    [GetHashKey('WEAPON_HAMMER')]        = 'Hammer',
    [GetHashKey('WEAPON_BAT')]           = 'Bat',
    [GetHashKey('WEAPON_CROWBAR')]       = 'Crowbar',
    [GetHashKey('WEAPON_GOLFCLUB')]      = 'Golf Club',
    [GetHashKey('WEAPON_BOTTLE')]        = 'Bottle',
    [GetHashKey('WEAPON_DAGGER')]        = 'Dagger',
    [GetHashKey('WEAPON_HATCHET')]       = 'Hatchet',
    [GetHashKey('WEAPON_KNUCKLE')]       = 'Knuckle Duster',
    [GetHashKey('WEAPON_MACHETE')]       = 'Machete',
    [GetHashKey('WEAPON_FLASHLIGHT')]    = 'Flashlight',
    [GetHashKey('WEAPON_SWITCHBLADE')]   = 'Switchblade',
    [GetHashKey('WEAPON_POOLCUE')]       = 'Pool Cue',
    [GetHashKey('WEAPON_WRENCH')]        = 'Wrench',
    [GetHashKey('WEAPON_BATTLEAXE')]     = 'Battle Axe',
    [GetHashKey('WEAPON_STONE_HATCHET')] = 'Stone Hatchet',
    [GetHashKey('WEAPON_PISTOL')]          = 'Pistol',
    [GetHashKey('WEAPON_PISTOL_MK2')]      = 'Pistol Mk2',
    [GetHashKey('WEAPON_COMBATPISTOL')]    = 'Combat Pistol',
    [GetHashKey('WEAPON_APPISTOL')]        = 'AP Pistol',
    [GetHashKey('WEAPON_STUNGUN')]         = 'Stun Gun',
    [GetHashKey('WEAPON_PISTOL50')]        = 'Pistol .50',
    [GetHashKey('WEAPON_SNSPISTOL')]       = 'SNS Pistol',
    [GetHashKey('WEAPON_SNSPISTOL_MK2')]   = 'SNS Pistol Mk2',
    [GetHashKey('WEAPON_HEAVYPISTOL')]     = 'Heavy Pistol',
    [GetHashKey('WEAPON_VINTAGEPISTOL')]   = 'Vintage Pistol',
    [GetHashKey('WEAPON_FLAREGUN')]        = 'Flare Gun',
    [GetHashKey('WEAPON_MARKSMANPISTOL')]  = 'Marksman Pistol',
    [GetHashKey('WEAPON_REVOLVER')]        = 'Revolver',
    [GetHashKey('WEAPON_REVOLVER_MK2')]    = 'Revolver Mk2',
    [GetHashKey('WEAPON_DOUBLEACTION')]    = 'Double Action Revolver',
    [GetHashKey('WEAPON_CERAMICPISTOL')]   = 'Ceramic Pistol',
    [GetHashKey('WEAPON_NAVYREVOLVER')]    = 'Navy Revolver',
    [GetHashKey('WEAPON_GADGETPISTOL')]    = 'Perico Pistol',
    [GetHashKey('WEAPON_MICROSMG')]      = 'Micro SMG',
    [GetHashKey('WEAPON_SMG')]           = 'SMG',
    [GetHashKey('WEAPON_SMG_MK2')]       = 'SMG Mk2',
    [GetHashKey('WEAPON_ASSAULTSMG')]    = 'Assault SMG',
    [GetHashKey('WEAPON_COMBATPDW')]     = 'Combat PDW',
    [GetHashKey('WEAPON_MACHINEPISTOL')] = 'Machine Pistol',
    [GetHashKey('WEAPON_MINISMG')]       = 'Mini SMG',
    [GetHashKey('WEAPON_PUMPSHOTGUN')]      = 'Pump Shotgun',
    [GetHashKey('WEAPON_PUMPSHOTGUN_MK2')]  = 'Pump Shotgun Mk2',
    [GetHashKey('WEAPON_SAWNOFFSHOTGUN')]   = 'Sawed-Off Shotgun',
    [GetHashKey('WEAPON_ASSAULTSHOTGUN')]   = 'Assault Shotgun',
    [GetHashKey('WEAPON_BULLPUPSHOTGUN')]   = 'Bullpup Shotgun',
    [GetHashKey('WEAPON_MUSKET')]           = 'Musket',
    [GetHashKey('WEAPON_HEAVYSHOTGUN')]     = 'Heavy Shotgun',
    [GetHashKey('WEAPON_DBSHOTGUN')]        = 'Double Barrel Shotgun',
    [GetHashKey('WEAPON_AUTOSHOTGUN')]      = 'Auto Shotgun',
    [GetHashKey('WEAPON_COMBATSHOTGUN')]    = 'Combat Shotgun',
    [GetHashKey('WEAPON_ASSAULTRIFLE')]         = 'Assault Rifle',
    [GetHashKey('WEAPON_ASSAULTRIFLE_MK2')]     = 'Assault Rifle Mk2',
    [GetHashKey('WEAPON_CARBINERIFLE')]         = 'Carbine Rifle',
    [GetHashKey('WEAPON_CARBINERIFLE_MK2')]     = 'Carbine Rifle Mk2',
    [GetHashKey('WEAPON_ADVANCEDRIFLE')]        = 'Advanced Rifle',
    [GetHashKey('WEAPON_SPECIALCARBINE')]       = 'Special Carbine',
    [GetHashKey('WEAPON_SPECIALCARBINE_MK2')]   = 'Special Carbine Mk2',
    [GetHashKey('WEAPON_BULLPUPRIFLE')]         = 'Bullpup Rifle',
    [GetHashKey('WEAPON_BULLPUPRIFLE_MK2')]     = 'Bullpup Rifle Mk2',
    [GetHashKey('WEAPON_COMPACTRIFLE')]         = 'Compact Rifle',
    [GetHashKey('WEAPON_MILITARYRIFLE')]        = 'Military Rifle',
    [GetHashKey('WEAPON_HEAVYRIFLE')]           = 'Heavy Rifle',
    [GetHashKey('WEAPON_TACTICALRIFLE')]        = 'Tactical Rifle',
    [GetHashKey('WEAPON_MG')]            = 'MG',
    [GetHashKey('WEAPON_COMBATMG')]      = 'Combat MG',
    [GetHashKey('WEAPON_COMBATMG_MK2')]  = 'Combat MG Mk2',
    [GetHashKey('WEAPON_GUSENBERG')]     = 'Gusenberg Sweeper',
    [GetHashKey('WEAPON_SNIPERRIFLE')]        = 'Sniper Rifle',
    [GetHashKey('WEAPON_HEAVYSNIPER')]        = 'Heavy Sniper',
    [GetHashKey('WEAPON_HEAVYSNIPER_MK2')]    = 'Heavy Sniper Mk2',
    [GetHashKey('WEAPON_MARKSMANRIFLE')]      = 'Marksman Rifle',
    [GetHashKey('WEAPON_MARKSMANRIFLE_MK2')]  = 'Marksman Rifle Mk2',
    [GetHashKey('WEAPON_PRECISIONRIFLE')]     = 'Precision Rifle',
    [GetHashKey('WEAPON_RPG')]              = 'RPG',
    [GetHashKey('WEAPON_GRENADELAUNCHER')]  = 'Grenade Launcher',
    [GetHashKey('WEAPON_MINIGUN')]          = 'Minigun',
    [GetHashKey('WEAPON_FIREWORK')]         = 'Firework',
    [GetHashKey('WEAPON_RAILGUN')]          = 'Railgun',
    [GetHashKey('WEAPON_HOMINGLAUNCHER')]   = 'Homing Launcher',
    [GetHashKey('WEAPON_COMPACTLAUNCHER')]  = 'Compact Launcher',
    [GetHashKey('WEAPON_RAYMINIGUN')]       = 'Widowmaker',
    [GetHashKey('WEAPON_EMPLAUNCHER')]      = 'EMP Launcher',
    [GetHashKey('WEAPON_GRENADE')]      = 'Grenade',
    [GetHashKey('WEAPON_BZGAS')]        = 'BZ Gas',
    [GetHashKey('WEAPON_MOLOTOV')]      = 'Molotov',
    [GetHashKey('WEAPON_STICKYBOMB')]   = 'Sticky Bomb',
    [GetHashKey('WEAPON_PROXMINE')]     = 'Proximity Mine',
    [GetHashKey('WEAPON_SNOWBALL')]     = 'Snowball',
    [GetHashKey('WEAPON_PIPEBOMB')]     = 'Pipe Bomb',
    [GetHashKey('WEAPON_SMOKEGRENADE')] = 'Smoke Grenade',
}

Config.WeaponCategories = {
    [GetHashKey('WEAPON_UNARMED')]       = 'melee',
    [GetHashKey('WEAPON_KNIFE')]         = 'melee',
    [GetHashKey('WEAPON_NIGHTSTICK')]    = 'melee',
    [GetHashKey('WEAPON_HAMMER')]        = 'melee',
    [GetHashKey('WEAPON_BAT')]           = 'melee',
    [GetHashKey('WEAPON_CROWBAR')]       = 'melee',
    [GetHashKey('WEAPON_GOLFCLUB')]      = 'melee',
    [GetHashKey('WEAPON_BOTTLE')]        = 'melee',
    [GetHashKey('WEAPON_DAGGER')]        = 'melee',
    [GetHashKey('WEAPON_HATCHET')]       = 'melee',
    [GetHashKey('WEAPON_KNUCKLE')]       = 'melee',
    [GetHashKey('WEAPON_MACHETE')]       = 'melee',
    [GetHashKey('WEAPON_FLASHLIGHT')]    = 'melee',
    [GetHashKey('WEAPON_SWITCHBLADE')]   = 'melee',
    [GetHashKey('WEAPON_POOLCUE')]       = 'melee',
    [GetHashKey('WEAPON_WRENCH')]        = 'melee',
    [GetHashKey('WEAPON_BATTLEAXE')]     = 'melee',
    [GetHashKey('WEAPON_STONE_HATCHET')] = 'melee',
    [GetHashKey('WEAPON_PISTOL')]          = 'pistol',
    [GetHashKey('WEAPON_PISTOL_MK2')]      = 'pistol',
    [GetHashKey('WEAPON_COMBATPISTOL')]    = 'pistol',
    [GetHashKey('WEAPON_APPISTOL')]        = 'pistol',
    [GetHashKey('WEAPON_STUNGUN')]         = 'pistol',
    [GetHashKey('WEAPON_PISTOL50')]        = 'pistol',
    [GetHashKey('WEAPON_SNSPISTOL')]       = 'pistol',
    [GetHashKey('WEAPON_SNSPISTOL_MK2')]   = 'pistol',
    [GetHashKey('WEAPON_HEAVYPISTOL')]     = 'pistol',
    [GetHashKey('WEAPON_VINTAGEPISTOL')]   = 'pistol',
    [GetHashKey('WEAPON_FLAREGUN')]        = 'pistol',
    [GetHashKey('WEAPON_MARKSMANPISTOL')]  = 'pistol',
    [GetHashKey('WEAPON_REVOLVER')]        = 'pistol',
    [GetHashKey('WEAPON_REVOLVER_MK2')]    = 'pistol',
    [GetHashKey('WEAPON_DOUBLEACTION')]    = 'pistol',
    [GetHashKey('WEAPON_CERAMICPISTOL')]   = 'pistol',
    [GetHashKey('WEAPON_NAVYREVOLVER')]    = 'pistol',
    [GetHashKey('WEAPON_GADGETPISTOL')]    = 'pistol',
    [GetHashKey('WEAPON_MICROSMG')]      = 'smg',
    [GetHashKey('WEAPON_SMG')]           = 'smg',
    [GetHashKey('WEAPON_SMG_MK2')]       = 'smg',
    [GetHashKey('WEAPON_ASSAULTSMG')]    = 'smg',
    [GetHashKey('WEAPON_COMBATPDW')]     = 'smg',
    [GetHashKey('WEAPON_MACHINEPISTOL')] = 'smg',
    [GetHashKey('WEAPON_MINISMG')]       = 'smg',
    [GetHashKey('WEAPON_PUMPSHOTGUN')]      = 'shotgun',
    [GetHashKey('WEAPON_PUMPSHOTGUN_MK2')]  = 'shotgun',
    [GetHashKey('WEAPON_SAWNOFFSHOTGUN')]   = 'shotgun',
    [GetHashKey('WEAPON_ASSAULTSHOTGUN')]   = 'shotgun',
    [GetHashKey('WEAPON_BULLPUPSHOTGUN')]   = 'shotgun',
    [GetHashKey('WEAPON_MUSKET')]           = 'shotgun',
    [GetHashKey('WEAPON_HEAVYSHOTGUN')]     = 'shotgun',
    [GetHashKey('WEAPON_DBSHOTGUN')]        = 'shotgun',
    [GetHashKey('WEAPON_AUTOSHOTGUN')]      = 'shotgun',
    [GetHashKey('WEAPON_COMBATSHOTGUN')]    = 'shotgun',
    [GetHashKey('WEAPON_ASSAULTRIFLE')]         = 'rifle',
    [GetHashKey('WEAPON_ASSAULTRIFLE_MK2')]     = 'rifle',
    [GetHashKey('WEAPON_CARBINERIFLE')]         = 'rifle',
    [GetHashKey('WEAPON_CARBINERIFLE_MK2')]     = 'rifle',
    [GetHashKey('WEAPON_ADVANCEDRIFLE')]        = 'rifle',
    [GetHashKey('WEAPON_SPECIALCARBINE')]       = 'rifle',
    [GetHashKey('WEAPON_SPECIALCARBINE_MK2')]   = 'rifle',
    [GetHashKey('WEAPON_BULLPUPRIFLE')]         = 'rifle',
    [GetHashKey('WEAPON_BULLPUPRIFLE_MK2')]     = 'rifle',
    [GetHashKey('WEAPON_COMPACTRIFLE')]         = 'rifle',
    [GetHashKey('WEAPON_MILITARYRIFLE')]        = 'rifle',
    [GetHashKey('WEAPON_HEAVYRIFLE')]           = 'rifle',
    [GetHashKey('WEAPON_TACTICALRIFLE')]        = 'rifle',
    [GetHashKey('WEAPON_MG')]            = 'rifle',
    [GetHashKey('WEAPON_COMBATMG')]      = 'rifle',
    [GetHashKey('WEAPON_COMBATMG_MK2')]  = 'rifle',
    [GetHashKey('WEAPON_GUSENBERG')]     = 'rifle',
    [GetHashKey('WEAPON_SNIPERRIFLE')]        = 'sniper',
    [GetHashKey('WEAPON_HEAVYSNIPER')]        = 'sniper',
    [GetHashKey('WEAPON_HEAVYSNIPER_MK2')]    = 'sniper',
    [GetHashKey('WEAPON_MARKSMANRIFLE')]      = 'sniper',
    [GetHashKey('WEAPON_MARKSMANRIFLE_MK2')]  = 'sniper',
    [GetHashKey('WEAPON_PRECISIONRIFLE')]     = 'sniper',
    [GetHashKey('WEAPON_RPG')]              = 'explosive',
    [GetHashKey('WEAPON_GRENADELAUNCHER')]  = 'explosive',
    [GetHashKey('WEAPON_MINIGUN')]          = 'explosive',
    [GetHashKey('WEAPON_FIREWORK')]         = 'explosive',
    [GetHashKey('WEAPON_RAILGUN')]          = 'explosive',
    [GetHashKey('WEAPON_HOMINGLAUNCHER')]   = 'explosive',
    [GetHashKey('WEAPON_COMPACTLAUNCHER')]  = 'explosive',
    [GetHashKey('WEAPON_RAYMINIGUN')]       = 'explosive',
    [GetHashKey('WEAPON_EMPLAUNCHER')]      = 'explosive',
    [GetHashKey('WEAPON_GRENADE')]          = 'explosive',
    [GetHashKey('WEAPON_BZGAS')]            = 'explosive',
    [GetHashKey('WEAPON_MOLOTOV')]          = 'explosive',
    [GetHashKey('WEAPON_STICKYBOMB')]       = 'explosive',
    [GetHashKey('WEAPON_PROXMINE')]         = 'explosive',
    [GetHashKey('WEAPON_PIPEBOMB')]         = 'explosive',
    [GetHashKey('WEAPON_SNOWBALL')]         = 'thrown',
    [GetHashKey('WEAPON_SMOKEGRENADE')]     = 'thrown',
    [GetHashKey('WEAPON_FALL')]                = 'environment',
    [GetHashKey('WEAPON_DROWNING')]            = 'environment',
    [GetHashKey('WEAPON_DROWNING_IN_VEHICLE')] = 'environment',
    [GetHashKey('WEAPON_FIRE')]                = 'environment',
    [GetHashKey('WEAPON_EXPLOSION')]           = 'environment',
    [GetHashKey('WEAPON_BLEEDING')]            = 'environment',
    [GetHashKey('WEAPON_ELECTRIC_FENCE')]      = 'environment',
    [GetHashKey('WEAPON_BARBED_WIRE')]         = 'environment',
    [GetHashKey('WEAPON_EXHAUSTION')]          = 'environment',
    [GetHashKey('WEAPON_RAMMED_BY_CAR')]       = 'vehicle',
    [GetHashKey('WEAPON_RUN_OVER_BY_CAR')]     = 'vehicle',
    [GetHashKey('WEAPON_VEHICLE')]             = 'vehicle',
    [GetHashKey('WEAPON_HIT_BY_WATER_CANNON')] = 'vehicle',
}

Config.WeaponHashNames = {}
for _, name in ipairs({
    'WEAPON_UNARMED', 'WEAPON_KNIFE', 'WEAPON_NIGHTSTICK', 'WEAPON_HAMMER', 'WEAPON_BAT',
    'WEAPON_CROWBAR', 'WEAPON_GOLFCLUB', 'WEAPON_BOTTLE', 'WEAPON_DAGGER', 'WEAPON_HATCHET',
    'WEAPON_KNUCKLE', 'WEAPON_MACHETE', 'WEAPON_FLASHLIGHT', 'WEAPON_SWITCHBLADE', 'WEAPON_POOLCUE',
    'WEAPON_WRENCH', 'WEAPON_BATTLEAXE', 'WEAPON_STONE_HATCHET', 'WEAPON_CANDYCANE', 'WEAPON_STUNROD',
    'WEAPON_PISTOL', 'WEAPON_PISTOL_MK2', 'WEAPON_COMBATPISTOL', 'WEAPON_APPISTOL', 'WEAPON_STUNGUN',
    'WEAPON_PISTOL50', 'WEAPON_SNSPISTOL', 'WEAPON_SNSPISTOL_MK2', 'WEAPON_HEAVYPISTOL',
    'WEAPON_VINTAGEPISTOL', 'WEAPON_FLAREGUN', 'WEAPON_MARKSMANPISTOL', 'WEAPON_REVOLVER',
    'WEAPON_REVOLVER_MK2', 'WEAPON_DOUBLEACTION', 'WEAPON_CERAMICPISTOL', 'WEAPON_NAVYREVOLVER',
    'WEAPON_GADGETPISTOL', 'WEAPON_PISTOLXM3', 'WEAPON_TECPISTOL',
    'WEAPON_MICROSMG', 'WEAPON_SMG', 'WEAPON_SMG_MK2', 'WEAPON_ASSAULTSMG', 'WEAPON_COMBATPDW',
    'WEAPON_MACHINEPISTOL', 'WEAPON_MINISMG',
    'WEAPON_PUMPSHOTGUN', 'WEAPON_PUMPSHOTGUN_MK2', 'WEAPON_SAWNOFFSHOTGUN', 'WEAPON_ASSAULTSHOTGUN',
    'WEAPON_BULLPUPSHOTGUN', 'WEAPON_MUSKET', 'WEAPON_HEAVYSHOTGUN', 'WEAPON_DBSHOTGUN',
    'WEAPON_AUTOSHOTGUN', 'WEAPON_COMBATSHOTGUN',
    'WEAPON_ASSAULTRIFLE', 'WEAPON_ASSAULTRIFLE_MK2', 'WEAPON_CARBINERIFLE', 'WEAPON_CARBINERIFLE_MK2',
    'WEAPON_ADVANCEDRIFLE', 'WEAPON_SPECIALCARBINE', 'WEAPON_SPECIALCARBINE_MK2', 'WEAPON_BULLPUPRIFLE',
    'WEAPON_BULLPUPRIFLE_MK2', 'WEAPON_COMPACTRIFLE', 'WEAPON_MILITARYRIFLE', 'WEAPON_HEAVYRIFLE',
    'WEAPON_TACTICALRIFLE', 'WEAPON_BATTLERIFLE',
    'WEAPON_MG', 'WEAPON_COMBATMG', 'WEAPON_COMBATMG_MK2', 'WEAPON_GUSENBERG', 'WEAPON_RAYCARBINE',
    'WEAPON_SNIPERRIFLE', 'WEAPON_HEAVYSNIPER', 'WEAPON_HEAVYSNIPER_MK2', 'WEAPON_MARKSMANRIFLE',
    'WEAPON_MARKSMANRIFLE_MK2', 'WEAPON_PRECISIONRIFLE',
    'WEAPON_RPG', 'WEAPON_GRENADELAUNCHER', 'WEAPON_GRENADELAUNCHER_SMOKE', 'WEAPON_MINIGUN',
    'WEAPON_FIREWORK', 'WEAPON_RAILGUN', 'WEAPON_HOMINGLAUNCHER', 'WEAPON_COMPACTLAUNCHER',
    'WEAPON_RAYMINIGUN', 'WEAPON_EMPLAUNCHER', 'WEAPON_RAILGUNXM3', 'WEAPON_SNOWLAUNCHER',
    'WEAPON_GRENADE', 'WEAPON_BZGAS', 'WEAPON_MOLOTOV', 'WEAPON_STICKYBOMB', 'WEAPON_PROXMINE',
    'WEAPON_SNOWBALL', 'WEAPON_PIPEBOMB', 'WEAPON_SMOKEGRENADE', 'WEAPON_FLARE', 'WEAPON_BALL',
    'WEAPON_PETROLCAN', 'WEAPON_FIREEXTINGUISHER', 'WEAPON_HAZARDCAN', 'WEAPON_FERTILIZERCAN',
    'WEAPON_FALL', 'WEAPON_DROWNING', 'WEAPON_DROWNING_IN_VEHICLE', 'WEAPON_FIRE', 'WEAPON_EXPLOSION',
    'WEAPON_BLEEDING', 'WEAPON_ELECTRIC_FENCE', 'WEAPON_BARBED_WIRE', 'WEAPON_EXHAUSTION',
    'WEAPON_HIT_BY_WATER_CANNON', 'WEAPON_RAMMED_BY_CAR', 'WEAPON_RUN_OVER_BY_CAR', 'WEAPON_VEHICLE',
}) do
    Config.WeaponHashNames[GetHashKey(name)] = name:lower()
end

function GetWeaponLabel(hash)
    if not hash or hash == 0 then return 'Unknown' end
    return Config.WeaponLabels[hash] or 'Unknown'
end

function GetWeaponCategory(hash)
    if not hash or hash == 0 then return 'unknown' end
    return Config.WeaponCategories[hash] or 'unknown'
end

function GetWeaponHashName(hash)
    if not hash or hash == 0 then return nil end
    return Config.WeaponHashNames[hash]
end
