AddTextEntry("WEAPON_GLOCK19GEN4", "Glock 19 Gen 4")
AddTextEntry("WEAPON_GLOCK20", "Glock 20")
AddTextEntry("WEAPON_HK417", "HK417")
AddTextEntry("WEAPON_KS1", "KAC KS-1")
AddTextEntry("WEAPON_LBRS", "LB-RS")
AddTextEntry("WEAPON_LWRC", "LWRC")
AddTextEntry("WEAPON_FM1_BENELLIM4", "Benelli M4")
AddTextEntry("WEAPON_P90", "P-90")
AddTextEntry("WEAPON_SIG516", "Sig 516")
AddTextEntry("WEAPON_SIG_SAUCER", "Sig Saucer")
