AddTextEntry("WEAPON_MP9A", "MP9")
AddTextEntry("WEAPON_FBIARB", "FBI AR-15")
AddTextEntry("WEAPON_HK416B", "HK-416")
AddTextEntry("WEAPON_GHOSTARP", "Ghost ARP")
AddTextEntry("WEAPON_GHOSTGLOCK", "Ghost Glock")
AddTextEntry("WEAPON_AIRSOFTR870", "Airsoft R870")
AddTextEntry("WEAPON_AIRSOFTM4", "Airsoft M4")
AddTextEntry("WEAPON_AIRSOFTGLOCK20", "Airsoft Glock 20")
AddTextEntry("WEAPON_PAINTBALL", "PaintBall Weapon")
AddTextEntry("WEAPON_GAS", "Galaxy Gas")
AddTextEntry("WEAPON_BEANBAG", "Beanbag Shotgun")
AddTextEntry("WEAPON_M6IC", "LWRC M6IC")
AddTextEntry("WEAPON_MP5SDFM", "MP5-SD")
AddTextEntry("WEAPON_FURYNAILBAT", "Nail Bat")
AddTextEntry("WEAPON_SCARSC", "Scar SC")
AddTextEntry("WEAPON_SR47", "SR-47")
AddTextEntry("WEAPON_BK_aAP", "BK AP")
AddTextEntry("WEAPON_BK_MPX", "BK MPX")
AddTextEntry("WEAPON_PINK", "Pink Glock")
AddTextEntry("WEAPON_KOIFISH", "Koi SMG")
AddTextEntry("WEAPON_YAKUZASMG", "Dragon SMG")
