const config = {}

config.brandsLogos = {
    ['-']: null,
    ['Albany']: 'Albany.webp',
    ['Annis']: 'Annis.webp',
    ['Benefactor']: 'Benefactor.webp',
    ['Bollokan']: 'Bollokan.webp',
    ['Bravado']: 'Bravado.webp',
    ['Brute']: 'Brute.webp',
    ['Buckingham']: 'Buckingham.webp',
    ['Bürgerfahrzeug']: 'Burgerfahrzeug.webp',
    ['Canis']: 'Canis.webp',
    ['Chariot']: 'Chariot.webp',
    ['Cheval']: 'Cheval.webp',
    ['Classique']: 'Classique.webp',
    ['Coil']: 'Coil.webp',
    ['Declasse']: 'Declasse.webp',
    ['Dewbauchee']: 'Dewbauchee.webp',
    ['Dinka']: 'Dinka.png',
    ['Dundreary']: 'Dundreary.webp',
    ['Emperor']: 'Emperor.webp',
    ['Enus']: 'Enus.webp',
    ['Fathom']: 'Fathom.webp',
    ['Gallivanter']: 'Gallivanter.webp',
    ['Grotti']: 'Grotti.webp',
    ['Hijak']: 'Hijak.webp',
    ['HVY']: 'HVY.webp',
    ['Imponte']: 'Impote.webp',
    ['Invetero']: 'Invetero.webp',
    ['JoBuilt']: 'JoBuilt.webp',
    ['Karin']: 'Karin.webp',
    ['Kraken Submersibles']: 'KrakenSubmersibles.webp',
    ['Lampadati']: 'Lampadati.webp',
    ['Liberty City Cycles']: 'LCC.webp',
    ['Maibatsu Corporation']: 'Maibatsu.webp',
    ['Mammoth']: 'Mammoth.webp',
    ['Maxwell']: 'Maxwell.webp',
    ['MTL']: 'MTL.webp',
    ['Nagasaki']: 'Nagasaki.webp',
    ['Obey']: 'Obey.webp',
    ['Ocelot']: 'Ocelot.webp',
    ['Överflöd']: 'Overflod.webp',
    ['Pegassi']: 'Pegassi.webp',
    ['Penaud']: '',
    ['Pfister']: 'Pfister.webp',
    ['Principe']: 'Principe.webp',
    ['Progen']: 'Progen.webp',
    ['RUNE']: 'RUNE.webp',
    ['Schyster']: 'Schyster.webp',
    ['Shitzu']: 'Shitzu.webp',
    ['Speedophile']: 'Speedophile.webp',
    ['Stanley']: 'Stanley.webp',
    ['Steel Horse']: 'SteelHorse.webp',
    ['Toundra']: 'Toundra.webp',
    ['Truffade']: 'Truffade.webp',
    ['Übermacht']: 'Ubermacht.webp',
    ['Vapid']: 'Vapid.webp',
    ['Vulcar']: 'Vulcar.webp',
    ['Vysser']: 'Vysser.webp',
    ['Weeny']: 'Weeny.webp',
    ['Western Company']: 'WC.webp',
    ['Western Motorcycle Company']: 'WMC.webp',
    ['Willard']: '',
    ['Zirconium']: 'Zirconium.webp',
}

config.colorsList = [
    {label: "Metallic Black", id: 0},
    {label: "Matte Black", id: 12},
    {label: "Carbon", id: 147},

    {label: "Metallic Cream", id: 107},
    {label: "Metallic White", id: 111},
    {label: "Pure White", id: 134},
    
    {label: "Metallic Silver", id: 4},
    {label: "Matte Gray", id: 13},
    {label: "Metallic Champagne", id: 93},

    {label: "Metallic Red", id: 27},
    {label: "Metallic Candy Red", id: 35},
    {label: "Matte Red", id: 39},

    {label: "Hot Pink", id: 135},

    {label: "Metallic Dark Blue", id: 62},
    {label: "Metallic Blue", id: 64},
    {label: "Matte Blue", id: 83},
    
    {label: "Matte Yellow", id: 42},
    {label: "Metallic Taxi Yellow", id: 88},
    
    {label: "Metallic Green", id: 53},
    {label: "Util Green", id: 57},
    {label: "Matte Green", id: 55},

    {label: "Metallic Orange", id: 38},
    {label: "Metallic Sunrise Orange", id: 36},
    {label: "Matte Orange", id: 41},

    {label: "Metallic Bronze", id: 90},
    {label: "Metallic Straw Beige", id: 99},
    {label: "Matte Brown", id: 129},
    
    {label: "Metallic Purple", id: 145},
    {label: "Metallic Purple Blue", id: 71},
    {label: "Matte Purple", id: 148},
]