--If you want to remove a weapon, delete it from this list
Config.headshotMultiplier = 3.0
Config.weapons = {
    ["nass_paintball_gun"] = {label = "Paintball Gun", damage = 20},
    ["WEAPON_REVOLVER"] = {label = "Revolver", damage = 37},
    ["WEAPON_PISTOL"] = {label = "Pistol", damage = 15},
    ["WEAPON_PISTOL_MK2"] = {label = "Pistol Mk2", damage = 20},
    ["WEAPON_COMBATPISTOL"] = {label = "Combatpistol", damage = 25},
    ["WEAPON_APPISTOL"] = {label = "AP Pistol", damage = 20},
    ["WEAPON_PISTOL50"] = {label = "Pistol 50", damage = 40},
    ["WEAPON_SNSPISTOL"] = {label = "SNS Pistol", damage = 15},
    ["WEAPON_HEAVYPISTOL"] = {label = "Heavy Pistol", damage = 40},
    ["WEAPON_VINTAGEPISTOL"] = {label = "Vintage Pistol", damage = 30},
    ["WEAPON_MARKSMANPISTOL"] = {label = "Marksman Pistol", damage = 30},
    ["WEAPON_MICROSMG"] = {label = "Micro SMG", damage = 20},
    ["WEAPON_MINISMG"] = {label = "Mini SMG", damage = 20},
    ["WEAPON_SMG"] = {label = "SMG", damage = 20},
    ["WEAPON_SMG_MK2"] = {label = "SMG Mk2", damage = 20},
    ["WEAPON_ASSAULTSMG"] = {label = "Assault SMG", damage = 20},
    ["WEAPON_MG"] = {label = "MG", damage = 20},
    ["WEAPON_COMBATMG"] = {label = "Combat MG", damage = 20},
    ["WEAPON_COMBATMG_MK2"] = {label = "Combat MG Mk2", damage = 20},
    ["WEAPON_COMBATPDW"] = {label = "Combat PDW", damage = 20},
    ["WEAPON_GUSENBERG"] = {label = "Gusenberg", damage = 20},
    ["WEAPON_MACHINEPISTOL"] = {label = "Machine Pistol", damage = 20},
    ["WEAPON_ASSAULTRIFLE"] = {label = "Assault Rifle", damage = 20},
    ["WEAPON_ASSAULTRIFLE_MK2"] = {label = "Assault Rifle Mk2", damage = 20},
    ["WEAPON_CARBINERIFLE"] = {label = "Carbine Rifle", damage = 20},
    ["WEAPON_CARBINERIFLE_MK2"] = {label = "Carbine Rifle Mk2", damage = 20},
    ["WEAPON_ADVANCEDRIFLE"] = {label = "Advanced Rifle", damage = 20},
    ["WEAPON_SPECIALCARBINE"] = {label = "Special Carbine", damage = 20},
    ["WEAPON_BULLPUPRIFLE"] = {label = "Bullpup Rifle", damage = 20},
    ["WEAPON_COMPACTRIFLE"] = {label = "Compact Rifle", damage = 20},
    ["WEAPON_PUMPSHOTGUN"] = {label = "Pump Shotgun", damage = 60},
    ["WEAPON_SAWNOFFSHOTGUN"] = {label = "Sawnoff Shotgun", damage = 40},
    ["WEAPON_BULLPUPSHOTGUN"] = {label = "Bullpup Shotgun", damage = 50},
    ["WEAPON_ASSAULTSHOTGUN"] = {label = "Assault Shotgun", damage = 60},
    ["WEAPON_MUSKET"] = {label = "Musket", damage = 120},
    ["WEAPON_HEAVYSHOTGUN"] = {label = "Heavy Shotgun", damage = 40},
    ["WEAPON_DBSHOTGUN"] = {label = "DB Shotgun", damage = 40},
    ["WEAPON_SNIPERRIFLE"] = {label = "Sniper Rifle", damage = 200},
    ["WEAPON_HEAVYSNIPER"] = {label = "Heavy Sniper", damage = 200},
    ["WEAPON_HEAVYSNIPER_MK2"] = {label = "Heavy Sniper Mk2", damage = 200},
    ["WEAPON_MARKSMANRIFLE"] = {label = "Marksman Rifle", damage = 200},
    ["WEAPON_SNSPISTOL_MK2"] = {label = "SNS Pistol Mk2", damage = 17},
    ["WEAPON_REVOLVER_MK2"] = {label = "Revolver Mk2", damage = 40},
    ["WEAPON_DOUBLEACTION"] = {label = "Double Action", damage = 30},
    ["WEAPON_SPECIALCARBINE_MK2"] = {label = "Special Carbine Mk2", damage = 20},
    ["WEAPON_BULLPUPRIFLE_MK2"] = {label = "Bullpup Rifle Mk2", damage = 20},
    ["WEAPON_PUMPSHOTGUN_MK2"] = {label = "Pump Shotgun Mk2", damage = 20},
    ["WEAPON_MARKSMANRIFLE_MK2"] = {label = "Marksman Rifle Mk2", damage = 20},
    ["WEAPON_RAYPISTOL"] = {label = "Ray Pistol", damage = 20},
    ["WEAPON_RAYCARBINE"] = {label = "Ray Carbine", damage = 20},
    ["WEAPON_RAYMINIGUN"] = {label = "Ray Minigun", damage = 20},
    ["WEAPON_NAVYREVOLVER"] = {label = "Navy Revolver", damage = 20},
    ["WEAPON_MILITARYRIFLE"] = {label = "Military Rifle", damage = 20},
    ["WEAPON_COMBATSHOTGUN"] = {label = "Combat Shotgun", damage = 20},
    ["WEAPON_AUTOSHOTGUN"] = {label = "Auto Shotgun", damage = 30},
}


Config.gunGameWeapons = { --Must be in Config.weapons
    "WEAPON_REVOLVER",
    "WEAPON_PISTOL",
    "WEAPON_COMBATPISTOL",
    "WEAPON_APPISTOL",
    "WEAPON_MICROSMG",
    "WEAPON_SMG",
    "WEAPON_ASSAULTSMG",
    "WEAPON_COMBATPDW",
    "WEAPON_GUSENBERG",
    "WEAPON_ASSAULTRIFLE",
    "WEAPON_CARBINERIFLE",
    "WEAPON_ADVANCEDRIFLE",
    "WEAPON_SPECIALCARBINE",
    "WEAPON_BULLPUPRIFLE",
    "WEAPON_COMPACTRIFLE",
    "WEAPON_PUMPSHOTGUN",
    "WEAPON_ASSAULTSHOTGUN",
    "WEAPON_MUSKET",
    "WEAPON_HEAVYSNIPER_MK2",
    "WEAPON_RAYPISTOL",
    "nass_paintball_gun",
}