function AddVehicleEntry(key, value)
    Citizen.InvokeNative(GetHashKey("ADD_TEXT_ENTRY"), key, value)
end

Citizen.CreateThread(function()
    AddVehicleEntry("RS7", "RS7")
    AddVehicleEntry("Maxima", "Maxima")
    AddVehicleEntry("M5", "M5 e39")
    AddVehicleEntry("M3", "M3 g80")
    AddVehicleEntry("Flying Spur", "Flying Spur")
    AddVehicleEntry("GT", "2017 GT")
    AddVehicleEntry("SS", "SS")
    AddVehicleEntry("Urus", "Urus SE")
    AddVehicleEntry("Lanzador", "Lanzador")
    AddVehicleEntry("jesko", "Jesko")
    AddVehicleEntry("765LT", "765 LT")
    AddVehicleEntry("G8", "G8")
    AddVehicleEntry("Veyron", "Veyron")
    AddVehicleEntry("Trackhawk", "Trackhawk")
    AddVehicleEntry("F5", "F5")
    AddVehicleEntry("M2", "M2")
    AddVehicleEntry("R7", "R7")
    AddVehicleEntry("Revuelto", "Revuelto")
    AddVehicleEntry("C8", "C8")
    AddVehicleEntry("GT 500", "GT500")
    AddVehicleEntry("Raptor", "Raptor")
    AddVehicleEntry("67 Mustang", "67 Mustang")
    AddVehicleEntry("Turbo GT", "Turbo GT")
    AddVehicleEntry("87 Mustang", "87 Mustang")
    AddVehicleEntry("M3", "M3 f80")
    AddVehicleEntry("R1", "R1")
    AddVehicleEntry("A3", "A3")
    AddVehicleEntry("RCF", "RCF")
    AddVehicleEntry("RS5", "RS5")
    AddVehicleEntry("S4 Avant", "S4 Avant")

    -- New Dealership
    AddVehicleEntry("Sierra", "Sierra")
    AddVehicleEntry("Camaro SS", "Camaro SS")
    AddVehicleEntry("F-150 Raptor", "F-150 Raptor")
    AddVehicleEntry("Yukon", "Yukon")
    AddVehicleEntry("F450", "F-450 Platinum")
    AddVehicleEntry("718 GT4RS", "718 GT4RS")
    AddVehicleEntry("M5 CS", "M5 CS")
    AddVehicleEntry("Mach EGT", "Mach EGT")
    AddVehicleEntry("Sierra", "Sierra")
    AddVehicleEntry("Tacoma Base", "Tacoma Base")
    AddVehicleEntry("Tacoma", "Tacoma")
    AddVehicleEntry("Escalade V", "Escalade V")
    AddVehicleEntry("Tahoe z71", "Tahoe z71")
    AddVehicleEntry("Tundra TRD PRO", "Tundra TRD PRO")
    AddVehicleEntry("Tacoma TRD", "Tacoma TRD")
    AddVehicleEntry("2500 Long Horn", "2500 Long Horn")
    AddVehicleEntry("Camaro RS", "Camaro RS")
    AddVehicleEntry("Silverado RST", "Silverado RST")
    AddVehicleEntry("Demon", "Demon")
    AddVehicleEntry("Sierra AT4", "Sierra AT4")
    AddVehicleEntry("Explorer", "Explorer")
    AddVehicleEntry("Hiliux RS", "Hiliux RS")
    AddVehicleEntry("GT3RS", "GT3RS")
    AddVehicleEntry("Pro Master", "Pro Master")
    AddVehicleEntry("GT3", "GT3")
end)