INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES
('weed_seed', 'Weed Seed', 40, 0, 1),
('gingeritis_weed', 'Wet Gingeritis Weed', 110, 0, 1),
('energizing_dried_weed', 'Energizing Dried Weed', 30, 0, 1),
('weed', 'Wet Weed', 100, 0, 1),
('high_quality_weed', 'Wet High Quality Weed', 100, 0, 1),
('dried_weed', 'Dried Weed', 20, 0, 1),
('dried_high_quality_weed', 'Dried High Quality Weed', 20, 0, 1),
('packaged_gingeritis_weed', 'Packaged Wet Gingeritis Weed', 110, 0, 1),
('packaged_energizing_dried_weed', 'Packaged Dried Energizing Weed', 40, 0, 1),
('packaged_weed', 'Packaged Wet Weed', 110, 0, 1),
('packaged_high_quality_weed', 'Packaged Wet High Quality Weed', 110, 0, 1),
('packaged_dried_weed', 'Packaged Dried Weed', 30, 0, 1),
('packaged_dried_high_quality_weed', 'Packaged Dried High Quality Weed', 20, 0, 1),
('coke_seed', 'Coke Seed', 40, 0, 1),
('coke_leaf', 'Wet Coke Leaf', 50, 0, 1),
('high_quality_coke_leaf', 'Wet High Quality Coke Leaf', 50, 0, 1),
('dried_coke_leaf', 'Dried Coke Leaf', 10, 0, 1),
('dried_high_quality_coke_leaf', 'Dried High Quality Coke Leaf', 10, 0, 1),
('coke', 'Wet Coke Base', 100, 0, 1),
('high_quality_coke', 'Wet High Quality Coke Base', 100, 0, 1),
('dried_coke', 'Dried Coke Base', 20, 0, 1),
('dried_high_quality_coke', 'Dried High Quality Coke Base', 20, 0, 1),
('cooked_coke', 'Wet Coke', 100, 0, 1),
('cooked_high_quality_coke', 'Wet High Quality Coke', 100, 0, 1),
('cooked_dried_coke', 'Dried Coke', 20, 0, 1),
('cooked_dried_high_quality_coke', 'Dried High Quality Coke', 20, 0, 1),
('packaged_coke', 'Packaged Wet Coke Base', 100, 0, 1),
('packaged_high_quality_coke', 'Packaged Wet High Quality Coke Base', 100, 0, 1),
('packaged_dried_coke', 'Packaged Dried Coke Base', 20, 0, 1),
('packaged_dried_high_quality_coke', 'Packaged Dried High Quality Coke Base', 20, 0, 1),
('packaged_cooked_coke', 'Packaged Wet Coke', 100, 0, 1),
('packaged_cooked_high_quality_coke', 'Packaged Wet High Quality Coke', 100, 0, 1),
('packaged_cooked_dried_coke', 'Packaged Dried Coke', 20, 0, 1),
('packaged_cooked_dried_high_quality_coke', 'Packaged Dried High Quality Coke', 20, 0, 1),
('liquid_meth', 'Liquid Meth', 200, 0, 1),
('default_meth', 'Meth Bud', 10, 0, 1),
('packaged_default_meth', 'Packaged Meth', 60, 0, 1),
('weed_brick', 'Weed Brick', 400, 0, 1),
('high_quality_weed_brick', 'High Quality Weed Brick', 400, 0, 1),
('coke_brick', 'Coke Base Brick', 500, 0, 1),
('high_quality_coke_brick', 'High Quality Coke Base Brick', 500, 0, 1),
('cooked_coke_brick', 'Coke Brick', 500, 0, 1),
('cooked_high_quality_coke_brick', 'Coke High Quality Brick', 500, 0, 1),
('baggy', 'Baggy', 10, 0, 1),
('plant_pot', 'Plant Pot', 100, 0, 1),
('fertilizer', 'Fertilizer', 1000, 0, 1),
('default_lamp', 'Lamp', 500, 0, 1),
('default_fan', 'Fan', 500, 0, 1),
('default_soil', 'Soil', 500, 0, 1),
('drying_rack', 'Drying Rack', 500, 0, 1),
('watering_can', 'Watering Can', 500, 0, 1),
('default_brick_press', 'Brick Press', 3500, 0, 1),
('packaging_station', 'Packaging Station', 5000, 0, 1),
('drug_mixer', 'Drug Mixer', 2000, 0, 1),
('plant_trimmers', 'Plant Trimmers', 200, 0, 1),
('drug_cauldron', 'Cauldron', 5000, 0, 1),
('drug_oven', 'Lab Oven', 5000, 0, 1),
('chemistry_station', 'Chemistry Station', 5000, 0, 1),
('acetone', 'Acetone', 500, 0, 1),
('ecola', 'E-Cola', 200, 0, 1),
('pills', 'Pseudo', 100, 0, 1),
('phosphorus', 'Phosphorus', 500, 0, 1),
('gasoline', 'Gasoline', 2000, 0, 1),
('banana', 'Banana', 100, 0, 1),
('hammer', 'Hammer', 1000, 0, 1);