CreateThread(function()
    AddTextEntry('wheel_custom_01', 'Blocco')
    AddTextEntry('wheel_custom_02', 'Denti')
    AddTextEntry('wheel_custom_03', 'Veraso')
    AddTextEntry('wheel_custom_04', 'Asheville')
    AddTextEntry('wheel_custom_05', 'Charlotte')
    AddTextEntry('wheel_custom_06', 'Myrtle')
    AddTextEntry('wheel_custom_07', 'Bio')
    AddTextEntry('wheel_custom_08', 'Dominion')
    AddTextEntry('wheel_custom_09', 'Empire')
    AddTextEntry('wheel_custom_10', 'Grip')
    AddTextEntry('wheel_custom_11', 'Guru')
    AddTextEntry('wheel_custom_12', 'Omen')
    AddTextEntry('wheel_custom_13', 'Pinnacle')
    AddTextEntry('wheel_custom_14', 'Prime')
    AddTextEntry('wheel_custom_15', 'Revolt')
    AddTextEntry('wheel_custom_16', 'Rumble')
    AddTextEntry('wheel_custom_17', 'Ace')
    AddTextEntry('wheel_custom_18', 'Bounty')
    AddTextEntry('wheel_custom_19', 'Compass')
    AddTextEntry('wheel_custom_20', 'Elixir')
    AddTextEntry('wheel_custom_21', 'Inject')
    AddTextEntry('wheel_custom_22', 'Ray')
    AddTextEntry('wheel_custom_23', 'Scuffle')
    AddTextEntry('wheel_custom_24', 'Swoop')
    AddTextEntry('wheel_custom_25', 'Valor')
    AddTextEntry('wheel_custom_26', 'Vile')
    AddTextEntry('wheel_custom_27', 'Bandit')
    AddTextEntry('wheel_custom_28', 'Buck')
    AddTextEntry('wheel_custom_29', 'Denver')
    AddTextEntry('wheel_custom_30', 'Roulette')
    AddTextEntry('wheel_custom_31', 'Spur')
    AddTextEntry('wheel_custom_32', 'Stampede')
    AddTextEntry('wheel_custom_33', 'Triumph')
    AddTextEntry('wheel_custom_34', 'Grin')
    AddTextEntry('wheel_custom_35', 'Shank')
    AddTextEntry('wheel_custom_36', 'Runner')
    AddTextEntry('wheel_custom_37', 'Assassin')
    AddTextEntry('wheel_custom_38', 'Maniac')
    AddTextEntry('wheel_custom_39', 'Trump')
    AddTextEntry('wheel_custom_40', 'Strappo')
    AddTextEntry('wheel_custom_41', 'XF009')
    AddTextEntry('wheel_custom_42', 'XF007')
    AddTextEntry('wheel_custom_43', 'Strike')
    AddTextEntry('wheel_custom_44', 'SF-6')
    AddTextEntry('wheel_custom_45', 'Ruthless 1')
    AddTextEntry('wheel_custom_46', 'Ruthless 2')
    AddTextEntry('wheel_custom_47', 'Nemesis')
    AddTextEntry('wheel_custom_48', 'AF-12')
    AddTextEntry('wheel_custom_49', 'AF01')
    AddTextEntry('wheel_custom_50', 'Curvus')

end)