-- Generated by Be Eazy Development

fx_version 'cerulean'
game { 'gta5' }

files {
  'peds.meta',
  'mp_m_freemode_01_mp_m_windy.meta',
  'mp_f_freemode_01_mp_f_windy.meta',
  'mp_m_freemode_01_mp_m_windy2.meta',
  'mp_f_freemode_01_mp_f_windy2.meta',
  'mp_m_freemode_01_mp_m_windy3.meta',
  'mp_f_freemode_01_mp_f_windy3.meta',
  'mp_m_freemode_01_mp_m_windy4.meta',
  'mp_f_freemode_01_mp_f_windy4.meta',
  'stream/pedalternatevariations.meta'
}

data_file 'PED_METADATA_FILE' 'peds.meta'
data_file 'SHOP_PED_APPAREL_META_FILE' 'mp_m_freemode_01_mp_m_windy.meta'
data_file 'SHOP_PED_APPAREL_META_FILE' 'mp_f_freemode_01_mp_f_windy.meta'
data_file 'SHOP_PED_APPAREL_META_FILE' 'mp_m_freemode_01_mp_m_windy2.meta'
data_file 'SHOP_PED_APPAREL_META_FILE' 'mp_f_freemode_01_mp_f_windy2.meta'
data_file 'SHOP_PED_APPAREL_META_FILE' 'mp_m_freemode_01_mp_m_windy3.meta'
data_file 'SHOP_PED_APPAREL_META_FILE' 'mp_f_freemode_01_mp_f_windy3.meta'
data_file 'SHOP_PED_APPAREL_META_FILE' 'mp_m_freemode_01_mp_m_windy4.meta'
data_file 'SHOP_PED_APPAREL_META_FILE' 'mp_f_freemode_01_mp_f_windy4.meta'
data_file 'ALTERNATE_VARIATIONS_FILE' 'stream/pedalternatevariations.meta'