return {
	search_name = '',
	search_vehicle = '',
	search_id = '',
	owner_set = '',
	owner_remove = '',
	owner_clear = '',
	owner_trade = '',
	owner_transfer = '',
	trust_give = '',
	trust_remove = '',
	trust_trade = '',
	trust_clear = '',
	transfer_data = '',
	admin_menu = '',
}