-- init locales
lib.locale()

Config = Config or {}

Config.Hitboxes = {
    ["head"] = { offset = vector3(0.15, -0.075, 0.6), size = vector3(0.3, 0.3, 0.3) },
    ["body"] = { offset = vector3(0.15, -0.075, 0.2), size = vector3(0.6, 0.5, 0.6) },
}

Config.Debug = false

Config.BoxingRings = {
}

Config.RingCorners = {
    vec4(-1.8, -1.6, 1.5, 50.0),
    vec4(1.8, 1.6, 1.5, -130.0),
}

Config.RingSpawnDistance = 200.0

Config.DefaultRoundCount = 3
Config.DefaultRoundTime = 180

Config.InviteDuration = 60 * 1000

Config.IntroductionAnims = {
    ["shadow_boxing"] = {
        dict = "anim@mp_player_intcelebrationmale@shadow_boxing",
        name = "shadow_boxing",
        label = locale("INTRO_SHADOW_BOXING")
    },
    ["cut_throat"] = {
        dict = "anim@mp_player_intcelebrationmale@cut_throat",
        name = "cut_throat",
        label = locale("INTRO_CUT_THROAT")
    },
    ["nose_pick"] = {
        dict = "anim@mp_player_intcelebrationmale@nose_pick",
        name = "nose_pick",
        label = locale("INTRO_NOSE_PICK")
    },
    ["blow_kiss"] = {
        dict = "anim@mp_player_intcelebrationmale@blow_kiss",
        name = "blow_kiss",
        label = locale("INTRO_BLOW_KISS"),
    },
    ["karate_chops"] = {
        dict = "anim@mp_player_intcelebrationmale@karate_chops",
        name = "karate_chops",
        label = locale("INTRO_KARATE_CHOPS"),
    }
}

Config.CelebrationAnims = {
    ["thumbs_up"] = {
        dict = "anim@mp_player_intcelebrationmale@thumbs_up",
        name = "thumbs_up",
        label = locale("CELEBRATION_THUMBS_UP")
    },
    ["chicken_taunt"] = {
        dict = "anim@mp_player_intcelebrationmale@chicken_taunt",
        name = "chicken_taunt",
        label = locale("CELEBRATION_CHICKEN_TAUNT")
    },
    ["jazz_hands"] = {
        dict = "anim@mp_player_intcelebrationmale@jazz_hands",
        name = "jazz_hands",
        label = locale("CELEBRATION_JAZZ_HANDS")
    }
}

Config.HitSoundVolume = 0.2

Config.WhooshSoundVolume = 0.05

Config.BellVolume = 0.2

Config.DefaultRestTime = 30

Config.RestAnimation = {
    dict = "rcm_barry3",
    anim = "barry_3_sit_loop"
}

Config.RestCorners = {
    vec4(-2.0, -1.8, 1.5, 50.0),
    vec4(2.0, 1.8, 1.5, -130.0),
}

Config.RingModels = {
    interior = `pr_boxingring_int`,
    exterior = `pr_boxingring_ext`,
}

if Config.OverrideRingModel then
    Config.RingModels.interior = Config.OverrideRingModel
    Config.RingModels.exterior = Config.OverrideRingModel
end

Config.RandomFirstNames = {
    "Aden",
    "Grayson",
    "Glenn",
    "Malachi",
    "Arron",
    "Ray",
    "Trystan",
    "Jarod",
    "Giovanny",
    "Royce",
    "Brian",
    "Kole",
    "Stone",
    "Hasan",
    "Cesar",
    "Arman",
    "Santos",
    "Rasheed",
    "Garett",
    "Christian",
    "Kain",
    "Deven",
    "Corey",
    "Armani",
    "Gaige",
    "Demarco",
    "Jayden",
    "Jakob",
    "Herbert",
    "Syed",
    "Eduardo",
    "Kalvin",
    "Harry",
    "Albert",
    "Timothy",
    "Bruce",
    "Chandler",
    "Luca",
    "Ricky",
    "Floyd",
    "Marco",
    "Alonso",
    "Sabastian",
    "Haden",
    "Paul",
    "Austyn",
    "Darin",
    "Kelvin",
    "Bowen",
    "Kentrell",
    "Zackery",
    "Clark",
    "Jerrod",
    "Dejuan",
    "Antonio",
    "Tate",
    "Raheem",
    "Fabian",
    "Cody",
    "Jaxson",
    "Mackenzie",
    "Garret",
    "Cameron",
    "Darryl",
    "Aaron",
    "Marquez",
    "Jovanny",
    "Brant",
    "Keyshawn",
    "Donavan",
    "Jarret",
    "Ronaldo",
    "Daveon",
    "Carl",
    "Skyler",
    "Winston",
    "Darren",
    "Allan",
    "Destin",
    "Toby",
    "Tyreke",
    "Liam",
    "Benjamin",
    "Aldo",
    "Mike",
    "Draven",
    "Sherman",
    "Raymundo",
    "Kavon",
    "Jadon",
    "Cade",
    "Deion",
    "Moses",
    "Infant",
    "Johnson",
    "Bernardo",
    "Oliver",
    "Pierre",
    "Dallas",
    "Darien",
    "Judah",
    "Nathanial",
    "Miguel",
    "Juancarlos",
    "Keshon",
    "Galen",
    "Ruben",
    "Justus",
    "Sam",
    "Bradley",
    "Yisroel",
    "Alex",
    "Dominique",
    "Oswaldo",
    "Jasper",
    "Ahmad",
    "Larry",
    "Javion",
    "Kristofer",
    "Brendon",
    "Elliot",
    "Dexter",
    "Esteban",
    "Cristobal",
    "Mustafa",
    "Mario",
    "Lucas",
    "Jadyn",
    "Mordechai",
    "Randy",
    "Angel",
    "Rayshawn",
    "Cullen",
    "Jonah",
    "Charlie",
    "Kai",
    "Cory",
    "Franco",
    "Tavian",
    "Patrick",
    "Aubrey",
    "Hakeem",
    "Leroy",
    "Keaton",
    "Nestor",
    "Montana",
    "Gilbert",
    "Dusty",
    "Jan",
    "Damien",
    "Braydon",
    "Gerald",
    "Kalob",
    "Alton",
    "Ramon",
    "Anderson",
    "Tristin",
    "Noe",
    "Rodolfo",
    "Jamari",
    "Slade",
    "Dion",
    "Finn",
    "Arturo",
    "Niko",
    "Leland",
    "Terrance",
    "Jimmie",
    "August",
    "Rahul",
    "Ladarius",
    "Elisha",
    "Alfredo",
    "Jayce",
    "Kelly",
    "Zachariah",
    "Pablo",
    "Isiah",
    "Cortez",
    "Rodrigo",
    "Daylon",
    "Lyle",
    "Leif",
    "Joseph",
    "Johnnie",
    "Dakotah",
    "Devin",
    "Roberto",
    "Salvador",
    "Issac",
    "Alberto",
    "Kenton",
    "Will",
    "Shamar",
    "Brett",
    "Phoenix",
    "William",
    "Vladimir",
    "Aron",
    "Jonathon",
    "Stephon",
    "Damion",
    "Courtney",
    "Howard",
    "Khalil",
    "Jorden",
    "Bryon",
    "Titus",
    "Ty",
    "Hamza",
    "Adrien",
    "Rodney",
    "Zachery",
    "Oscar",
    "Kerry",
    "Rylan",
    "Roland",
    "Asa",
    "Freddie",
    "Alek",
    "Carlo",
    "Mateo",
    "Carlton",
    "Payne",
    "Aiden",
    "Nigel",
    "Benito",
    "Wyatt",
    "Anthony",
    "Brennen",
    "Camron",
    "Silas",
    "Shaun",
    "Dandre",
    "Blaine",
    "Cale",
    "Isaac",
    "Zackary",
    "Zain",
    "Kyree",
    "Joel",
    "Zane",
    "Philip",
    "Santiago",
    "Nehemiah",
    "Jeffrey",
    "Darrin",
    "Nelson",
    "Malik"
}

Config.RandomLastNames = {
    "Paz",
    "Desai",
    "McIntire",
    "Russo",
    "Lemke",
    "Crowell",
    "Aguilera",
    "Barone",
    "Weller",
    "Ybarra",
    "McBride",
    "Popp",
    "Greenwood",
    "Middleton",
    "Townsend",
    "Larkin",
    "Rowland",
    "Harwood",
    "Salisbury",
    "Lanning",
    "Do",
    "Sanchez",
    "McCrary",
    "Dykes",
    "Fitzpatrick",
    "Koenig",
    "Craven",
    "Ray",
    "Medley",
    "Allred",
    "Hwang",
    "Hoover",
    "Ouellette",
    "Crowe",
    "Mojica",
    "Linares",
    "Gamboa",
    "Rhodes",
    "Connor",
    "Finch",
    "Croft",
    "Bender",
    "Parris",
    "Cannon",
    "Pierson",
    "Isom",
    "Anguiano",
    "Bueno",
    "Brown",
    "Ulloa",
    "Coats",
    "Villareal",
    "Callaway",
    "Bowling",
    "Amaro",
    "Cardenas",
    "Cloud",
    "Harms",
    "Crooks",
    "Blackburn",
    "Tubbs",
    "McCabe",
    "Lazo",
    "Ferreira",
    "Donahue",
    "Kaiser",
    "Medlin",
    "Simons",
    "Watts",
    "Bratton",
    "Ketchum",
    "Thomson",
    "Lapointe",
    "Libby",
    "Kline",
    "Carbajal",
    "Hester",
    "Heath",
    "Clawson",
    "Squires",
    "Nobles",
    "Bolin",
    "Barragan",
    "Grimm",
    "Kincaid",
    "Gant",
    "Godfrey",
    "Goss",
    "Boyd",
    "Pennington",
    "Shepard",
    "Leggett",
    "Pickering",
    "Worden",
    "McCarter",
    "Redd",
    "Donald",
    "Nugent",
    "Stock",
    "Downing",
    "Blount",
    "Magee",
    "Feldman",
    "Figueroa",
    "Young",
    "Rosenthal",
    "Park",
    "Boudreaux",
    "Sprague",
    "Wilburn",
    "Downs",
    "Waugh",
    "Sheridan",
    "Koehler",
    "Cullen",
    "Betts",
    "Packer",
    "Puckett",
    "Greenberg",
    "Riggs",
    "Doan",
    "Jankowski",
    "Jernigan",
    "Newell",
    "Beatty",
    "Taggart",
    "Batson",
    "Parr",
    "Prewitt",
    "Pacheco",
    "Piazza",
    "Schulte",
    "Capps",
    "Colby",
    "Hamm",
    "Meyers",
    "Harkins",
    "Song",
    "Duran",
    "Le",
    "Denny",
    "Bianco",
    "Soriano",
    "Moe",
    "Hinds",
    "Armendariz",
    "Baldwin",
    "Shapiro",
    "Shanks",
    "Ferrer",
    "Wilhelm",
    "Luke",
    "Bartley",
    "Fontenot",
    "Porter",
    "Rosado",
    "Quigley",
    "Lovett",
    "Sabo",
    "Lyon",
    "Harter",
    "Briscoe",
    "Galindo",
    "Grooms",
    "Ricks",
    "Rosario",
    "Low",
    "Gil",
    "Mcmillian",
    "Champion",
    "Biggs",
    "Yanez",
    "Eason",
    "Sample",
    "Tirado",
    "Carbone",
    "Devore",
    "Mahon",
    "Jameson",
    "Sandlin",
    "Dion",
    "Cooney",
    "Gaffney",
    "Peek",
    "Adamson",
    "Canady",
    "Menendez",
    "Ramos",
    "Hancock",
    "Moreland",
    "Barnes",
    "Hurt",
    "Bond",
    "Reis",
    "Montague",
    "Gipson",
    "Laws",
    "Maier",
    "Montano",
    "McDonnell",
    "Pearce",
    "Hyman",
    "Stewart",
    "Moya",
    "Hager",
    "Aguirre",
    "Potts",
    "Paredes",
    "Becerra",
    "Sewell",
    "Monson",
    "Ripley",
    "Fernandes",
    "Ohara",
    "Jett",
    "Bradley",
    "Mahoney",
    "Kish",
    "Aleman",
    "Crook",
    "Jaeger",
    "Gunn",
    "Goldberg",
    "Saxton",
    "Parnell",
    "Couture",
    "Newkirk",
    "Talley",
    "Hayward",
    "Mcneely",
    "Lowery",
    "Petrie",
    "Daniels",
    "Paxton",
    "Dailey",
    "Hadley",
    "Bonilla",
    "Gooden",
    "Derosa",
    "Gilley",
    "Covarrubias",
    "Shaw",
    "Martin",
    "Esposito",
    "Speer",
    "Walton",
    "Roy",
    "Pedraza",
    "Zarate"
}
